name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12

      - name: Install dependencies
        run: npm i -g swagger-jsdoc

      - name: Generate openapi document
        run: yarn openapi
      
      - name: Upload OpenAPI Artifact
        uses: actions/upload-artifact@v2
        with:
          name: openapi-json
          path: openapi/openapi.json
